trigger: none
pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'This is pipeline 2'
